### ISSUE TITLE
Refactoring: restructure the pages

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/doc#26]
the different .adoc files are a bit confusing IMO, for example overview.adoc is only for assertj-core when the site is meant for all modules, moreover some file are starting to be quite big and are not handy to work with (I'm looking at you assertions-guide.adoc!)

we should come with more obvious structure, here's a suggestion:
* rename overview.adoc to assertj-overview.adoc and give a quick overview for all modules
* one file per module if the module is small 
* several files for core, maybe one per chapter:
  - quick start
  - release notes
  - core assertions guide (might need to split further per assertions type, String, Iterables, ...
  - ...

**Comment by benoitdupont** [comment]
Hello, 

I tried to do this in https://github.com/assertj/doc/pull/30, hope it's what you described.

Here are several additional remarks:

1. I had some issues with IntelliJ IDEA formatting: it seems that the original files sometimes have a single space at the end of lines, that is automatically removed by IntelliJ. I re-added them, but I'm not sure that Intellij is wrong here.
2. This refactoring added an extra level of indentation:
    * Before: ===== (level 5) was in the TOC, without an automatic numbering
    * After: There's a ====== (level 6) which is not in the TOC anymore (but there's still an anchor)
3. _AssertJ sample project_ section should be at the same level than the other modules maybe ? https://github.com/joel-costigliola/assertj-examples seems to be multi-modules 
4. _Javadoc_ section maybe should be put at level 2 ? (at the same level than _2.2 Getting Help_ for example)
