### ISSUE TITLE
Links to assertj-core repository broken (master vs. main)

### ISSUE THREAD

**Issue by Riggs333** [assertj/doc#61]
There are some links to the `master` branch of the assertj-core repository. The `master` branch seems to be renamed to `main`.

A search for "master" in the docs repo reveals a list of files containing those broken links:
https://github.com/assertj/doc/search?q=master&unscoped_q=master
* src/docs/asciidoc/user-guide/assertj-core-samples.adoc
* src/docs/asciidoc/user-guide/assertj-db.adoc
* src/docs/asciidoc/user-guide/assertj-core-migration.adoc
* src/docs/asciidoc/user-guide/assertj-db-quickstart.adoc
* src/docs/asciidoc/user-guide/assertj-db-concepts.adoc

I propose to fix those broken links using the already existing AsciiDoc variable `current-branch` in the [link_attributes.adoc](https://github.com/assertj/doc/blob/1723e5accdcf062c30abb5fff7fc404bbb46a910/src/docs/asciidoc/link-attributes.adoc#L7).

A little downside (is it?) would be that all those links then use the URI https://github.com/joel-costigliola/assertj-examples instead of https://raw.githubusercontent.com/joel-costigliola/assertj-core/master. (I'd personally go for it since the user should manage to get the raw content by themselves. ;-))

What do you think?
I'd be happy to create a PR for that.

**Comment by scordio** [comment]
@Riggs333 nice catch, I agree with your proposal.  It would be great if you could take care of it!
