### ISSUE TITLE
PredicateAssert should permit testing of null 

### ISSUE THREAD

**Issue by cameronbraid** [assertj/doc#65]
AbstractPredicateAssert.accepts and rejects throws on null value.  It should not do this, since it stops me testing if my Predicate correctly handles null value. Since predicates cant be parameterised with primitives, Predicate<Boolean> must handle the case of null.

```
Predicate<Boolean> isTrue = v -> v == null ? false : v;
assertThat(isTrue).rejects(null); 
```

instead I get

```
java.lang.NullPointerException
	at org.assertj.core.api.AbstractPredicateAssert.rejects(AbstractPredicateAssert.java:88)
	at org.assertj.core.api.PredicateAssert.rejects(PredicateAssert.java:40)
```

**Comment by scordio** [comment]
Hi @cameronbraid, this repository contains the website of AssertJ, while this issue is for [assertj-core](https://github.com/joel-costigliola/assertj-core).

I opened joel-costigliola/assertj-core#1969 to track it.

**Comment by cameronbraid** [comment]
AAh, sorry mate.. and thanks for transferring it over.
