### ISSUE TITLE
Document migration path from single array to 2D array assertions introduced in 3.17.0

### ISSUE THREAD

**Issue by mipper** [assertj/doc#98]
#### Summary
The `hasSize(int)` method is no longer available on 2D arrays after commit assertj/assertj-core@a36275ecd89ffa12cca931e65b3c9e4fa5322f7f which was released as part of 3.17.0.

I have no idea whether other methods have also become unavailable on this, not whether other array classes are affected.

#### Example
This test will compile under 3.16.1 but not on any version after that up to 3.18.1.

```java
package org.asserj;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class HasSizeTest
{
    @Test
    public void shouldAnswerWithTrue()
    {
        assertThat(new String[][] { { "1" } }).hasSize(1);
    }
}
```

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue

**Comment by scordio** [comment]
Mapping between old and new assertions:

| 2D assertion before 3.17.0 | 2D assertion after 3.17.0 |
|----------------------------|---------------------------|
| `hasSize`                  | `hasDimensions`           |
|                            |                           |
|                            |                           |
|                            |                           |
